project:
  type: website
  output-dir: docs

website:
  title: "Parva Fazeli"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



